// <auto-generated />
using System;
using CompanyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyAPI.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20250830130456_ChangeDateColumnsToDateType")]
    partial class ChangeDateColumnsToDateType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyAPI.Models.Cabang", b =>
                {
                    b.Property<int>("CabangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabangID"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KodePos")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Kota")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NamaCabang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CabangID");

                    b.ToTable("Cabang");

                    b.HasData(
                        new
                        {
                            CabangID = 1,
                            Alamat = "Jl. Jend. Sudirman Kav. 52-53",
                            KodePos = "12190",
                            Kota = "Jakarta Selatan",
                            NamaCabang = "Kantor Pusat"
                        },
                        new
                        {
                            CabangID = 2,
                            Alamat = "Jl. Asia Afrika No. 1",
                            KodePos = "40111",
                            Kota = "Bandung",
                            NamaCabang = "Cabang Bandung"
                        },
                        new
                        {
                            CabangID = 3,
                            Alamat = "Jl. Basuki Rahmat No. 129-131",
                            KodePos = "60271",
                            Kota = "Surabaya",
                            NamaCabang = "Cabang Surabaya"
                        },
                        new
                        {
                            CabangID = 4,
                            Alamat = "Jl. Imam Bonjol No. 17",
                            KodePos = "20112",
                            Kota = "Medan",
                            NamaCabang = "Cabang Medan"
                        },
                        new
                        {
                            CabangID = 5,
                            Alamat = "Jl. Sultan Hasanuddin No. 5",
                            KodePos = "90111",
                            Kota = "Makassar",
                            NamaCabang = "Cabang Makassar"
                        },
                        new
                        {
                            CabangID = 6,
                            Alamat = "Jl. Malioboro No. 60",
                            KodePos = "55213",
                            Kota = "Yogyakarta",
                            NamaCabang = "Cabang Yogyakarta"
                        },
                        new
                        {
                            CabangID = 7,
                            Alamat = "Jl. Gajah Mada No. 1",
                            KodePos = "50134",
                            Kota = "Semarang",
                            NamaCabang = "Cabang Semarang"
                        },
                        new
                        {
                            CabangID = 8,
                            Alamat = "Jl. Teuku Umar No. 220",
                            KodePos = "80114",
                            Kota = "Denpasar",
                            NamaCabang = "Cabang Denpasar"
                        },
                        new
                        {
                            CabangID = 9,
                            Alamat = "Jl. Jend. Sudirman No. 123",
                            KodePos = "30129",
                            Kota = "Palembang",
                            NamaCabang = "Cabang Palembang"
                        },
                        new
                        {
                            CabangID = 10,
                            Alamat = "Jl. Jend. Sudirman No. 45",
                            KodePos = "76114",
                            Kota = "Balikpapan",
                            NamaCabang = "Cabang Balikpapan"
                        });
                });

            modelBuilder.Entity("CompanyAPI.Models.Jabatan", b =>
                {
                    b.Property<int>("JabatanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JabatanID"));

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NamaJabatan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JabatanID");

                    b.ToTable("Jabatan");

                    b.HasData(
                        new
                        {
                            JabatanID = 1,
                            Deskripsi = "Manages a team or department.",
                            NamaJabatan = "Manager"
                        },
                        new
                        {
                            JabatanID = 2,
                            Deskripsi = "Designs, develops, and maintains software.",
                            NamaJabatan = "Software Engineer"
                        },
                        new
                        {
                            JabatanID = 3,
                            Deskripsi = "Ensures the quality of software through testing.",
                            NamaJabatan = "Quality Assurance"
                        },
                        new
                        {
                            JabatanID = 4,
                            Deskripsi = "Manages employee relations and recruitment.",
                            NamaJabatan = "Human Resources"
                        },
                        new
                        {
                            JabatanID = 5,
                            Deskripsi = "Manages financial records and transactions.",
                            NamaJabatan = "Accountant"
                        },
                        new
                        {
                            JabatanID = 6,
                            Deskripsi = "Oversees projects from initiation to completion.",
                            NamaJabatan = "Project Manager"
                        },
                        new
                        {
                            JabatanID = 7,
                            Deskripsi = "Analyzes business needs and processes.",
                            NamaJabatan = "Business Analyst"
                        },
                        new
                        {
                            JabatanID = 8,
                            Deskripsi = "Designs user interfaces and user experiences.",
                            NamaJabatan = "UI/UX Designer"
                        },
                        new
                        {
                            JabatanID = 9,
                            Deskripsi = "Manages infrastructure and deployment pipelines.",
                            NamaJabatan = "DevOps Engineer"
                        },
                        new
                        {
                            JabatanID = 10,
                            Deskripsi = "Analyzes and interprets complex data.",
                            NamaJabatan = "Data Scientist"
                        });
                });

            modelBuilder.Entity("CompanyAPI.Models.Pegawai", b =>
                {
                    b.Property<int>("PegawaiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PegawaiID"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CabangID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("JabatanID")
                        .HasColumnType("int");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomorTelepon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusKontrak")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TanggalHabisKontrak")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("date");

                    b.HasKey("PegawaiID");

                    b.HasIndex("CabangID");

                    b.HasIndex("JabatanID");

                    b.ToTable("Pegawai");

                    b.HasData(
                        new
                        {
                            PegawaiID = 1,
                            Alamat = "Jl. Merdeka No. 10",
                            CabangID = 1,
                            Email = "budi.santoso@example.com",
                            JabatanID = 1,
                            NamaLengkap = "Budi Santoso",
                            NomorTelepon = "081234567890",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 2,
                            Alamat = "Jl. Pahlawan No. 5",
                            CabangID = 1,
                            Email = "ani.yudhoyono@example.com",
                            JabatanID = 2,
                            NamaLengkap = "Ani Yudhoyono",
                            NomorTelepon = "081234567891",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2028, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1990, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 3,
                            Alamat = "Jl. Kenanga No. 25",
                            CabangID = 2,
                            Email = "cici.paramida@example.com",
                            JabatanID = 3,
                            NamaLengkap = "Cici Paramida",
                            NomorTelepon = "081234567892",
                            StatusKontrak = "Contract",
                            TanggalHabisKontrak = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2019, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 4,
                            Alamat = "Jl. Mawar No. 15",
                            CabangID = 3,
                            Email = "doni.kusuma@example.com",
                            JabatanID = 4,
                            NamaLengkap = "Doni Kusuma",
                            NomorTelepon = "081234567893",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1988, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2017, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 5,
                            Alamat = "Jl. Melati No. 30",
                            CabangID = 4,
                            Email = "eka.sari@example.com",
                            JabatanID = 5,
                            NamaLengkap = "Eka Sari",
                            NomorTelepon = "081234567894",
                            StatusKontrak = "Contract",
                            TanggalHabisKontrak = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1995, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2020, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 6,
                            Alamat = "Jl. Anggrek No. 12",
                            CabangID = 5,
                            Email = "fajar.nugraha@example.com",
                            JabatanID = 6,
                            NamaLengkap = "Fajar Nugraha",
                            NomorTelepon = "081234567895",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1987, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2016, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 7,
                            Alamat = "Jl. Cendana No. 8",
                            CabangID = 6,
                            Email = "gita.gutawa@example.com",
                            JabatanID = 7,
                            NamaLengkap = "Gita Gutawa",
                            NomorTelepon = "081234567896",
                            StatusKontrak = "Intern",
                            TanggalHabisKontrak = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1993, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 8,
                            Alamat = "Jl. Flamboyan No. 3",
                            CabangID = 7,
                            Email = "hadi.pranoto@example.com",
                            JabatanID = 8,
                            NamaLengkap = "Hadi Pranoto",
                            NomorTelepon = "081234567897",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2028, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1989, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2018, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 9,
                            Alamat = "Jl. Dahlia No. 21",
                            CabangID = 8,
                            Email = "indah.permata@example.com",
                            JabatanID = 9,
                            NamaLengkap = "Indah Permata",
                            NomorTelepon = "081234567898",
                            StatusKontrak = "Contract",
                            TanggalHabisKontrak = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1996, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 10,
                            Alamat = "Jl. Istana No. 1",
                            CabangID = 9,
                            Email = "joko.widodo@example.com",
                            JabatanID = 10,
                            NamaLengkap = "Joko Widodo",
                            NomorTelepon = "081234567899",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1984, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2014, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PegawaiID = 11,
                            Alamat = "Jl. Bunga No. 9",
                            CabangID = 10,
                            Email = "kiki.amalia@example.com",
                            JabatanID = 1,
                            NamaLengkap = "Kiki Amalia",
                            NomorTelepon = "081234567880",
                            StatusKontrak = "Permanent",
                            TanggalHabisKontrak = new DateTime(2029, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalLahir = new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CompanyAPI.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchProcessId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("CompanyAPI.Models.Pegawai", b =>
                {
                    b.HasOne("CompanyAPI.Models.Cabang", "Cabang")
                        .WithMany("Pegawai")
                        .HasForeignKey("CabangID");

                    b.HasOne("CompanyAPI.Models.Jabatan", "Jabatan")
                        .WithMany("Pegawai")
                        .HasForeignKey("JabatanID");

                    b.Navigation("Cabang");

                    b.Navigation("Jabatan");
                });

            modelBuilder.Entity("CompanyAPI.Models.Cabang", b =>
                {
                    b.Navigation("Pegawai");
                });

            modelBuilder.Entity("CompanyAPI.Models.Jabatan", b =>
                {
                    b.Navigation("Pegawai");
                });
#pragma warning restore 612, 618
        }
    }
}
